#%RAML 1.0 SecurityScheme

description: |
  A custom security scheme for authenticating requests.
type: x-custom
describedBy:
  headers:
    SpecialToken:
      description: |
        Used to send a custom token.
      type: string
  responses:
    401:
      description: |
        Bad token.
    403: